feeds:
  - https://vnexpress.net/rss/so-hoa.rss
  - https://thanhnien.vn/cong-nghe/rss.html
  - https://tuoitre.vn/rss/cong-nghe.rss
  - https://dantri.com.vn/rss/cong-nghe.rss

html_sites:
  # Danh mục HTML (không phải RSS) – sẽ crawl nhẹ nhàng
  - name: dantri_ai_internet
    url: https://dantri.com.vn/cong-nghe/ai-internet.htm
  - name: tuoitre_congnghe
    url: https://tuoitre.vn/cong-nghe.htm

keywords:
  - AI
  - trí tuệ nhân tạo
  - công nghệ
  - robot
  - machine learning
