sources:
  # RSS
  - https://vnexpress.net/rss/so-hoa.rss
  - https://thanhnien.vn/cong-nghe/rss.html
  - https://tuoitre.vn/rss/cong-nghe.rss
  - https://dantri.com.vn/rss/cong-nghe.rss
  - https://ictnews.vietnamnet.vn/rss/ict.rss
  - https://genk.vn/rss/home.rss
  - https://zingnews.vn/rss/cong-nghe.rss
  - https://viettimes.vn/rss/cong-nghe.rss
  - https://nld.com.vn/rss/cong-nghe.rss
  - https://vtc.vn/rss/cong-nghe.rss
  - https://soha.vn/rss-cong-nghe.rss
  - https://vatvostudio.vn/category/artificial-intelligence.rss

  # HTML (tự phát hiện)
  - https://vnexpress.net/khoa-hoc-cong-nghe/ai
  - https://dantri.com.vn/cong-nghe/ai-internet.htm
  - https://tuoitre.vn/cong-nghe.htm

keywords:
  - AI
  - trí tuệ nhân tạo
  - công nghệ
  - robot
  - machine learning
  - deep learning
  - chip
