feeds:
  - https://thanhnien.vn/cong-nghe/rss.html
  - https://tuoitre.vn/rss/cong-nghe.rss
  - https://dantri.com.vn/cong-nghe/ai-internet.htm
  - https://tuoitre.vn/cong-nghe.htm
  - https://ictnews.vietnamnet.vn/rss/ict.rss
  - https://genk.vn/rss.chn
  - https://cafef.vn/thi-truong-cong-nghe.rss
  - https://baomoi.com/rss/cong-nghe.rss
  - https://kenh14.vn/cong-nghe.rss
  - https://zingnews.vn/cong-nghe.rss
  - https://viettimes.vn/rss/cong-nghe.rss
  - https://nld.com.vn/rss/cong-nghe.rss
  - https://vtc.vn/rss/cong-nghe.rss
  - https://soha.vn/cong-nghe.rss

keywords:
  - AI
  - trí tuệ nhân tạo
  - công nghệ
  - robot
  - machine learning
