name: Collect Analytics
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: "3.10"
      - name: Install deps
        run: pip install requests
      - name: Run analytics
        env:
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python analytics.py
      - name: Upload analytics
        uses: actions/upload-artifact@v4
        with:
          name: analytics
          path: analytics.json
