name: Auto Post to Facebook

on:
  schedule:
    - cron: "0 1 * * *"   # chạy 8h sáng VN (1h UTC)
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  auto-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run auto post
        run: python auto_post.py
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
